name = "ThreeBodyDecays"
uuid = "e6563dab-9ca1-5843-bde3-2ccf38d63843"
authors = ["Misha Mikhasenko <mikhail.mikhasenko@cern.ch>"]
version = "0.12.3"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PartialWaveFunctions = "793d2195-304b-438e-bbb1-bc33c872ac39"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
Parameters = "0.12.0"
PartialWaveFunctions = "0.2.0"
PolynomialRoots = "1.0.0"
Polynomials = "4.0.6"
RecipesBase = "1.3.0"
StaticArrays = "1.9.2"
Tullio = "0.3.0"
julia = "1.7"
